import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiOutlineGithub}  from 'react-icons/ai'
import Image from 'next/image'
import dev from '../public/ludzik.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

import rw from '../public/rw.png';
import wa from '../public/wa.png';
import urb from '../public/urb.png';
import sa from '../public/sa.png';

import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mateusz W Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 text-black md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>MatDev</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl'/></li>
            </ul>
          </nav>
          <div className='text-center p-10 dark:text-white'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Mateusz Wrycza</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Front-End Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>
self-taught, who is constantly developing by investing in courses and creating new projects</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://github.com/Regnar110'><AiOutlineGithub /></a>
          </div>
          <div className='relative md:h-96 md:w-96 mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={dev} layout="fill" objectFit='cover' alt="dev"/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} alt="design"/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Writing code</h3>
              <p className='py-2'>
              I create websites and applications using the Javascript programming language. I also use different tools that make my code more readable and easier to manage.
              </p>
              <h4 className='py-4 text-teal-600'>I am writing code using:</h4>
              <p className='text-gray-800 py-1 dark:text-white'>TypeScript</p>
              <p className='text-gray-800 py-1 dark:text-white'>React.js</p>
              <p className='text-gray-800 py-1 dark:text-white'>CSS/SCSS and a littlebit of TailWindCSS</p>
              <p className='text-gray-800 py-1 dark:text-white'>Node.js + Express.js</p>
              <p className='text-gray-800 py-1 dark:text-white'>PostgreSQL, MongoDB basics for data management</p>
              {/* <Image src={code} width={100} height={100} alt="code"/>
              <Image src={consulting} width={100} height={100} alt='consulting'/> */}
            </div>
            <div className='text-center flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100} alt="design"/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Responsive Web Design</h3>
              <p className='py-2 dark:text-white'>
                When creating websites and applications, I always work in such a way that they are adapted to both desktop and mobile devices
              </p>

              {/* <Image src={code} width={100} height={100} alt="code"/>
              <Image src={consulting} width={100} height={100} alt='consulting'/> */}
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I create projects using the above-mentioned technologies as well as using various supporting libraries and APIs. When writing code, I try to make it as clear and understandable as possible. My portfolio consists of projects written only by me, mainly using the React.js library.
              <br/>
              <span className='text-red-500'>WARNING </span>
              * Please note that the Urbanbin example project page below is outdated due to Heroku new payment policy. Later, Im going to convert the website to one that uses TypeScript and put the website server on google app engine.

            </p>
            {/* <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
              Tempora itaque, porro perspiciatis veritatis labore aliquid volupta0te in illo autem eaque temporibus.
            </p> */}
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='cursor-pointer basis-1/3 flex-1'>
              <a href='https://rw-test-site.netlify.app/'><Image src={rw} className='w-full h-full rounded-lg object-cover' alt='web1'/></a>
            </div>
            <div className='cursor-pointer basis-1/3 flex-1'>
              <a href="https://regnar110weatherapp.netlify.app/"><Image src={wa} className='w-full h-full rounded-lg object-cover' alt='web2'/></a>
            </div>
            <div className='cursor-pointer basis-1/3 flex-1'>
              <a href="https://starwarsthing.netlify.app/"><Image src={sa} className='w-full h-full rounded-lg object-cover' alt='web2'/></a>
            </div>
            <div className='cursor-pointer basis-1/3 flex-1'>
              <a href="https://urbanbin.netlify.app/#/"><Image src={urb} className='w-full h-full rounded-lg object-cover' alt='web3'/></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
